### ISSUE TITLE
jupyter notebooks

### ISSUE THREAD

**Issue by lauralwatkins** [spacetelescope/pylunch#13]
It was be great to have a session devoted to notebooks and the magical things they can do.

**Comment by lauralwatkins** [comment]
(Following a chat with @eteq.)

**Comment by ivastar** [comment]
We totally will: https://github.com/jakevdp/PythonDataScienceHandbook/blob/master/notebooks/01.03-Magic-Commands.ipynb

**Comment by eteq** [comment]
This was more-or-less covered in the session @ivastar mentions here.
