### ISSUE TITLE
Slack?

### ISSUE THREAD

**Issue by stholfeltz** [spacetelescope/pylunch#9]
I  was wondering if others thought it might be worth the time to discuss slack?
I just heard about it as a discussion / help forum (?) for python but I don't know anything about it. And I don't have a smart phone, so I can't access it using an app.

**Comment by eteq** [comment]
@stholfeltz - in just a few days supposedly ITSD is going to announce that slack is "official" and will start supporting it.  There's a "#python" channel there which is pretty high-traffic right now (substantially more than the pylunch mailing list).  Hopefully that'll do the job?

**Comment by eteq** [comment]
Oh, but you *might* be able to sign up right away at http://stsci.slack.com - the SSO thing is set up already so you should only need your stsci email.  (I'm not 100% sure if you can do that right now, but I imagine we'll hear more of the details shortly)

**Comment by eteq** [comment]
This happened as predicted, so closing this issue.
